// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hypersign/ssi/v1/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the ssi module's genesis state.
type GenesisState struct {
	ChainNamespace string  `protobuf:"bytes,1,opt,name=chainNamespace,proto3" json:"chainNamespace,omitempty"`
	Params         *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fdc77e3475ca247, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetChainNamespace() string {
	if m != nil {
		return m.ChainNamespace
	}
	return ""
}

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

// Param defines the ssi module's params.
type Params struct {
	RegisterDidFee              *types.Coin `protobuf:"bytes,1,opt,name=register_did_fee,json=registerDidFee,proto3" json:"register_did_fee,omitempty"`
	UpdateDidFee                *types.Coin `protobuf:"bytes,2,opt,name=update_did_fee,json=updateDidFee,proto3" json:"update_did_fee,omitempty"`
	DeactivateDidFee            *types.Coin `protobuf:"bytes,3,opt,name=deactivate_did_fee,json=deactivateDidFee,proto3" json:"deactivate_did_fee,omitempty"`
	RegisterCredentialSchemaFee *types.Coin `protobuf:"bytes,4,opt,name=register_credential_schema_fee,json=registerCredentialSchemaFee,proto3" json:"register_credential_schema_fee,omitempty"`
	UpdateCredentialSchemaFee   *types.Coin `protobuf:"bytes,5,opt,name=update_credential_schema_fee,json=updateCredentialSchemaFee,proto3" json:"update_credential_schema_fee,omitempty"`
	RegisterCredentialStatusFee *types.Coin `protobuf:"bytes,6,opt,name=register_credential_status_fee,json=registerCredentialStatusFee,proto3" json:"register_credential_status_fee,omitempty"`
	UpdateCredentialStatusFee   *types.Coin `protobuf:"bytes,7,opt,name=update_credential_status_fee,json=updateCredentialStatusFee,proto3" json:"update_credential_status_fee,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fdc77e3475ca247, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRegisterDidFee() *types.Coin {
	if m != nil {
		return m.RegisterDidFee
	}
	return nil
}

func (m *Params) GetUpdateDidFee() *types.Coin {
	if m != nil {
		return m.UpdateDidFee
	}
	return nil
}

func (m *Params) GetDeactivateDidFee() *types.Coin {
	if m != nil {
		return m.DeactivateDidFee
	}
	return nil
}

func (m *Params) GetRegisterCredentialSchemaFee() *types.Coin {
	if m != nil {
		return m.RegisterCredentialSchemaFee
	}
	return nil
}

func (m *Params) GetUpdateCredentialSchemaFee() *types.Coin {
	if m != nil {
		return m.UpdateCredentialSchemaFee
	}
	return nil
}

func (m *Params) GetRegisterCredentialStatusFee() *types.Coin {
	if m != nil {
		return m.RegisterCredentialStatusFee
	}
	return nil
}

func (m *Params) GetUpdateCredentialStatusFee() *types.Coin {
	if m != nil {
		return m.UpdateCredentialStatusFee
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "hypersign.ssi.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "hypersign.ssi.v1.Params")
}

func init() { proto.RegisterFile("hypersign/ssi/v1/genesis.proto", fileDescriptor_3fdc77e3475ca247) }

var fileDescriptor_3fdc77e3475ca247 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd3, 0xc1, 0x6a, 0xdb, 0x30,
	0x18, 0x07, 0xf0, 0xb8, 0xeb, 0x3c, 0xa6, 0x96, 0x10, 0xcc, 0x0e, 0x69, 0x37, 0x44, 0xe9, 0x61,
	0xf4, 0x52, 0x69, 0xce, 0x1e, 0x60, 0xb0, 0x8c, 0xf5, 0x32, 0xc6, 0x48, 0x6f, 0x3d, 0x2c, 0xc8,
	0xd2, 0x37, 0x5b, 0x10, 0x5b, 0xc6, 0x9f, 0x62, 0x96, 0xb7, 0xd8, 0x63, 0xed, 0xb6, 0x1c, 0x77,
	0x1c, 0xc9, 0x8b, 0x8c, 0x48, 0x8e, 0x33, 0x42, 0x82, 0x59, 0x6f, 0x46, 0x9f, 0xfe, 0x3f, 0xff,
	0x05, 0x12, 0xa1, 0xd9, 0xa2, 0x84, 0x0a, 0x75, 0x5a, 0x70, 0x44, 0xcd, 0xeb, 0x98, 0xa7, 0x50,
	0x00, 0x6a, 0x64, 0x65, 0x65, 0xac, 0x89, 0x06, 0xed, 0x9c, 0x21, 0x6a, 0x56, 0xc7, 0x97, 0x2f,
	0x52, 0x93, 0x1a, 0x37, 0xe4, 0x9b, 0x2f, 0xbf, 0xef, 0x92, 0x4a, 0x83, 0xb9, 0x41, 0x9e, 0x08,
	0x04, 0x5e, 0xc7, 0x09, 0x58, 0x11, 0x73, 0x69, 0x74, 0xe1, 0xe7, 0xd7, 0x19, 0x39, 0xbf, 0xf3,
	0xf0, 0xbd, 0x15, 0x16, 0xa2, 0xd7, 0xa4, 0x2f, 0x33, 0xa1, 0x8b, 0xcf, 0x22, 0x07, 0x2c, 0x85,
	0x84, 0x61, 0x70, 0x15, 0xdc, 0x3c, 0x9f, 0xec, 0xad, 0x46, 0x6f, 0x48, 0x58, 0x8a, 0x4a, 0xe4,
	0x38, 0x3c, 0xb9, 0x0a, 0x6e, 0xce, 0x46, 0x43, 0xb6, 0x5f, 0x88, 0x7d, 0x71, 0xf3, 0x49, 0xb3,
	0xef, 0xfa, 0xd7, 0x29, 0x09, 0xfd, 0x52, 0x34, 0x26, 0x83, 0x0a, 0x52, 0x8d, 0x16, 0xaa, 0xa9,
	0xd2, 0x6a, 0xfa, 0x0d, 0xfc, 0x6f, 0xce, 0x46, 0x17, 0xcc, 0xf7, 0x65, 0x9b, 0xbe, 0xac, 0xe9,
	0xcb, 0xc6, 0x46, 0x17, 0x93, 0xfe, 0x36, 0xf2, 0x41, 0xab, 0x8f, 0x00, 0xd1, 0x3b, 0xd2, 0x9f,
	0x97, 0x4a, 0x58, 0x68, 0x89, 0x93, 0x2e, 0xe2, 0xdc, 0x07, 0x1a, 0xe0, 0x8e, 0x44, 0x0a, 0x84,
	0xb4, 0xba, 0xfe, 0x17, 0x79, 0xd2, 0x85, 0x0c, 0x76, 0xa1, 0x06, 0xfa, 0x4a, 0x68, 0x7b, 0x1c,
	0x59, 0x81, 0x82, 0xc2, 0x6a, 0x31, 0x9b, 0xa2, 0xcc, 0x20, 0x17, 0x0e, 0x3d, 0xed, 0x42, 0x5f,
	0x6e, 0x81, 0x71, 0x9b, 0xbf, 0x77, 0xf1, 0x8d, 0xff, 0x40, 0x5e, 0x35, 0x27, 0x3d, 0xac, 0x3f,
	0xed, 0xd2, 0x2f, 0x7c, 0xfc, 0x90, 0x7d, 0xac, 0xbb, 0x15, 0x76, 0x8e, 0x4e, 0x0f, 0x1f, 0xd3,
	0xdd, 0xc5, 0x8f, 0x77, 0xdf, 0xe9, 0xcf, 0xfe, 0xbf, 0xfb, 0xd6, 0x7e, 0xff, 0xe9, 0xe7, 0x8a,
	0x06, 0xcb, 0x15, 0x0d, 0xfe, 0xac, 0x68, 0xf0, 0x63, 0x4d, 0x7b, 0xcb, 0x35, 0xed, 0xfd, 0x5e,
	0xd3, 0xde, 0xc3, 0x28, 0xd5, 0x36, 0x9b, 0x27, 0x4c, 0x9a, 0x9c, 0xb7, 0xf7, 0xf2, 0xd6, 0xdd,
	0x78, 0x69, 0x66, 0x3c, 0xd3, 0xea, 0xb6, 0x30, 0x0a, 0xf8, 0x77, 0xf7, 0xb8, 0xec, 0xa2, 0x04,
	0x4c, 0x42, 0x37, 0x7e, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x92, 0xb3, 0xfe, 0x19, 0x7a, 0x03,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainNamespace) > 0 {
		i -= len(m.ChainNamespace)
		copy(dAtA[i:], m.ChainNamespace)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ChainNamespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdateCredentialStatusFee != nil {
		{
			size, err := m.UpdateCredentialStatusFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.RegisterCredentialStatusFee != nil {
		{
			size, err := m.RegisterCredentialStatusFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.UpdateCredentialSchemaFee != nil {
		{
			size, err := m.UpdateCredentialSchemaFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RegisterCredentialSchemaFee != nil {
		{
			size, err := m.RegisterCredentialSchemaFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.DeactivateDidFee != nil {
		{
			size, err := m.DeactivateDidFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.UpdateDidFee != nil {
		{
			size, err := m.UpdateDidFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.RegisterDidFee != nil {
		{
			size, err := m.RegisterDidFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainNamespace)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RegisterDidFee != nil {
		l = m.RegisterDidFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.UpdateDidFee != nil {
		l = m.UpdateDidFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.DeactivateDidFee != nil {
		l = m.DeactivateDidFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.RegisterCredentialSchemaFee != nil {
		l = m.RegisterCredentialSchemaFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.UpdateCredentialSchemaFee != nil {
		l = m.UpdateCredentialSchemaFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.RegisterCredentialStatusFee != nil {
		l = m.RegisterCredentialStatusFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.UpdateCredentialStatusFee != nil {
		l = m.UpdateCredentialStatusFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainNamespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainNamespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterDidFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterDidFee == nil {
				m.RegisterDidFee = &types.Coin{}
			}
			if err := m.RegisterDidFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateDidFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateDidFee == nil {
				m.UpdateDidFee = &types.Coin{}
			}
			if err := m.UpdateDidFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeactivateDidFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeactivateDidFee == nil {
				m.DeactivateDidFee = &types.Coin{}
			}
			if err := m.DeactivateDidFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterCredentialSchemaFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterCredentialSchemaFee == nil {
				m.RegisterCredentialSchemaFee = &types.Coin{}
			}
			if err := m.RegisterCredentialSchemaFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialSchemaFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateCredentialSchemaFee == nil {
				m.UpdateCredentialSchemaFee = &types.Coin{}
			}
			if err := m.UpdateCredentialSchemaFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterCredentialStatusFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterCredentialStatusFee == nil {
				m.RegisterCredentialStatusFee = &types.Coin{}
			}
			if err := m.RegisterCredentialStatusFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialStatusFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateCredentialStatusFee == nil {
				m.UpdateCredentialStatusFee = &types.Coin{}
			}
			if err := m.UpdateCredentialStatusFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
