// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hypersign/ssi/v1/proof.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DocumentProof struct {
	Type               string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Created            string         `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	VerificationMethod string         `protobuf:"bytes,3,opt,name=verificationMethod,proto3" json:"verificationMethod,omitempty"`
	ProofPurpose       string         `protobuf:"bytes,4,opt,name=proofPurpose,proto3" json:"proofPurpose,omitempty"`
	ProofValue         string         `protobuf:"bytes,5,opt,name=proofValue,proto3" json:"proofValue,omitempty"`
	ClientSpecType     ClientSpecType `protobuf:"varint,6,opt,name=clientSpecType,proto3,enum=hypersign.ssi.v1.ClientSpecType" json:"clientSpecType,omitempty"`
}

func (m *DocumentProof) Reset()         { *m = DocumentProof{} }
func (m *DocumentProof) String() string { return proto.CompactTextString(m) }
func (*DocumentProof) ProtoMessage()    {}
func (*DocumentProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e66a03de5b4a6534, []int{0}
}
func (m *DocumentProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DocumentProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DocumentProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DocumentProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentProof.Merge(m, src)
}
func (m *DocumentProof) XXX_Size() int {
	return m.Size()
}
func (m *DocumentProof) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentProof.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentProof proto.InternalMessageInfo

func (m *DocumentProof) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DocumentProof) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *DocumentProof) GetVerificationMethod() string {
	if m != nil {
		return m.VerificationMethod
	}
	return ""
}

func (m *DocumentProof) GetProofPurpose() string {
	if m != nil {
		return m.ProofPurpose
	}
	return ""
}

func (m *DocumentProof) GetProofValue() string {
	if m != nil {
		return m.ProofValue
	}
	return ""
}

func (m *DocumentProof) GetClientSpecType() ClientSpecType {
	if m != nil {
		return m.ClientSpecType
	}
	return CLIENT_SPEC_TYPE_NONE
}

func init() {
	proto.RegisterType((*DocumentProof)(nil), "hypersign.ssi.v1.DocumentProof")
}

func init() { proto.RegisterFile("hypersign/ssi/v1/proof.proto", fileDescriptor_e66a03de5b4a6534) }

var fileDescriptor_e66a03de5b4a6534 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x33, 0x31,
	0x14, 0x85, 0x9b, 0xff, 0xaf, 0x15, 0x83, 0x16, 0xc9, 0x2a, 0x88, 0x84, 0x61, 0x56, 0xdd, 0x34,
	0xa1, 0xf5, 0x0d, 0xd4, 0x85, 0x0b, 0x85, 0x52, 0xc5, 0x85, 0x1b, 0x99, 0x66, 0x6e, 0x3b, 0x81,
	0xe9, 0x24, 0x24, 0x99, 0xc1, 0xbe, 0x85, 0x8f, 0xe5, 0xb2, 0x4b, 0x97, 0x32, 0xf3, 0x18, 0x6e,
	0x64, 0x52, 0x2c, 0xb6, 0xba, 0xcb, 0x3d, 0xe7, 0xbb, 0x97, 0x93, 0x83, 0xcf, 0xb3, 0x95, 0x01,
	0xeb, 0xd4, 0xa2, 0x10, 0xce, 0x29, 0x51, 0x8d, 0x84, 0xb1, 0x5a, 0xcf, 0xb9, 0xb1, 0xda, 0x6b,
	0x72, 0xba, 0x75, 0xb9, 0x73, 0x8a, 0x57, 0xa3, 0xb3, 0xf8, 0x17, 0x2f, 0x73, 0x05, 0x85, 0x7f,
	0x76, 0x06, 0xe4, 0x66, 0x2b, 0xfe, 0x44, 0xf8, 0xe4, 0x5a, 0xcb, 0x72, 0x09, 0x85, 0x9f, 0xb4,
	0xd7, 0x08, 0xc1, 0x5d, 0xbf, 0x32, 0x40, 0x51, 0x84, 0x06, 0x47, 0xd3, 0xf0, 0x26, 0x14, 0x1f,
	0x4a, 0x0b, 0x89, 0x87, 0x94, 0xfe, 0x0b, 0xf2, 0xf7, 0x48, 0x38, 0x26, 0x15, 0x58, 0x35, 0x57,
	0x32, 0xf1, 0x4a, 0x17, 0x77, 0xe0, 0x33, 0x9d, 0xd2, 0xff, 0x01, 0xfa, 0xc3, 0x21, 0x31, 0x3e,
	0x0e, 0xa1, 0x27, 0xa5, 0x35, 0xda, 0x01, 0xed, 0x06, 0x72, 0x47, 0x23, 0x0c, 0xe3, 0x30, 0x3f,
	0x26, 0x79, 0x09, 0xf4, 0x20, 0x10, 0x3f, 0x14, 0x72, 0x83, 0xfb, 0x9b, 0x8f, 0xdc, 0x1b, 0x90,
	0x0f, 0x6d, 0xd6, 0x5e, 0x84, 0x06, 0xfd, 0x71, 0xc4, 0xf7, 0x2b, 0xe0, 0x57, 0x3b, 0xdc, 0x74,
	0x6f, 0xef, 0xf2, 0xf6, 0xad, 0x66, 0x68, 0x5d, 0x33, 0xf4, 0x51, 0x33, 0xf4, 0xda, 0xb0, 0xce,
	0xba, 0x61, 0x9d, 0xf7, 0x86, 0x75, 0x9e, 0xc6, 0x0b, 0xe5, 0xb3, 0x72, 0xc6, 0xa5, 0x5e, 0x8a,
	0xed, 0xd5, 0x61, 0xe8, 0x4c, 0xea, 0x5c, 0x64, 0x2a, 0x1d, 0x16, 0x3a, 0x05, 0xf1, 0x12, 0xaa,
	0x6d, 0x4b, 0x72, 0xb3, 0x5e, 0xb0, 0x2f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x16, 0x7c, 0x70,
	0x3f, 0xa8, 0x01, 0x00, 0x00,
}

func (m *DocumentProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DocumentProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DocumentProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClientSpecType != 0 {
		i = encodeVarintProof(dAtA, i, uint64(m.ClientSpecType))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ProofValue) > 0 {
		i -= len(m.ProofValue)
		copy(dAtA[i:], m.ProofValue)
		i = encodeVarintProof(dAtA, i, uint64(len(m.ProofValue)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ProofPurpose) > 0 {
		i -= len(m.ProofPurpose)
		copy(dAtA[i:], m.ProofPurpose)
		i = encodeVarintProof(dAtA, i, uint64(len(m.ProofPurpose)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.VerificationMethod) > 0 {
		i -= len(m.VerificationMethod)
		copy(dAtA[i:], m.VerificationMethod)
		i = encodeVarintProof(dAtA, i, uint64(len(m.VerificationMethod)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Created) > 0 {
		i -= len(m.Created)
		copy(dAtA[i:], m.Created)
		i = encodeVarintProof(dAtA, i, uint64(len(m.Created)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintProof(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProof(dAtA []byte, offset int, v uint64) int {
	offset -= sovProof(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DocumentProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	l = len(m.Created)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	l = len(m.VerificationMethod)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	l = len(m.ProofPurpose)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	l = len(m.ProofValue)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	if m.ClientSpecType != 0 {
		n += 1 + sovProof(uint64(m.ClientSpecType))
	}
	return n
}

func sovProof(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProof(x uint64) (n int) {
	return sovProof(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DocumentProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DocumentProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DocumentProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Created = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationMethod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationMethod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofPurpose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofPurpose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientSpecType", wireType)
			}
			m.ClientSpecType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientSpecType |= ClientSpecType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProof(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProof
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProof
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProof
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProof
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProof        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProof          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProof = fmt.Errorf("proto: unexpected end of group")
)
