project_name: hid-node

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy -compat=1.19

builds:
  - id: ubuntu-amd64
    main: ./cmd/hid-noded
    binary: hid-noded
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=hid-node
      - -X github.com/cosmos/cosmos-sdk/version.AppName=hid-node
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}

  - id: ubuntu-arm64
    main: ./cmd/hid-noded
    binary: hid-noded
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.AppName=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}

  - id: darwin-amd64
    main: ./cmd/hid-noded
    binary: hid-noded
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.AppName=hid-node 
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}

archives:
  - id: release-archives
    format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: hypersign-protocol
    name: hid-node
  
  draft: false
  prerelease: false
  mode: append
  header: |
    # Release Notes
