// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: identityfee/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QuerySSIFeeRequest struct {
}

func (m *QuerySSIFeeRequest) Reset()         { *m = QuerySSIFeeRequest{} }
func (m *QuerySSIFeeRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySSIFeeRequest) ProtoMessage()    {}
func (*QuerySSIFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_657f65a9c7940d56, []int{0}
}
func (m *QuerySSIFeeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySSIFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySSIFeeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySSIFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySSIFeeRequest.Merge(m, src)
}
func (m *QuerySSIFeeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySSIFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySSIFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySSIFeeRequest proto.InternalMessageInfo

type QuerySSIFeeResponse struct {
	CreateDidFee                *types.Coin `protobuf:"bytes,1,opt,name=create_did_fee,json=createDidFee,proto3" json:"create_did_fee,omitempty"`
	UpdateDidFee                *types.Coin `protobuf:"bytes,2,opt,name=update_did_fee,json=updateDidFee,proto3" json:"update_did_fee,omitempty"`
	DeactivateDidFee            *types.Coin `protobuf:"bytes,3,opt,name=deactivate_did_fee,json=deactivateDidFee,proto3" json:"deactivate_did_fee,omitempty"`
	CreateSchemaFee             *types.Coin `protobuf:"bytes,4,opt,name=create_schema_fee,json=createSchemaFee,proto3" json:"create_schema_fee,omitempty"`
	RegisterCredentialStatusFee *types.Coin `protobuf:"bytes,5,opt,name=register_credential_status_fee,json=registerCredentialStatusFee,proto3" json:"register_credential_status_fee,omitempty"`
}

func (m *QuerySSIFeeResponse) Reset()         { *m = QuerySSIFeeResponse{} }
func (m *QuerySSIFeeResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySSIFeeResponse) ProtoMessage()    {}
func (*QuerySSIFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_657f65a9c7940d56, []int{1}
}
func (m *QuerySSIFeeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySSIFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySSIFeeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySSIFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySSIFeeResponse.Merge(m, src)
}
func (m *QuerySSIFeeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySSIFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySSIFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySSIFeeResponse proto.InternalMessageInfo

func (m *QuerySSIFeeResponse) GetCreateDidFee() *types.Coin {
	if m != nil {
		return m.CreateDidFee
	}
	return nil
}

func (m *QuerySSIFeeResponse) GetUpdateDidFee() *types.Coin {
	if m != nil {
		return m.UpdateDidFee
	}
	return nil
}

func (m *QuerySSIFeeResponse) GetDeactivateDidFee() *types.Coin {
	if m != nil {
		return m.DeactivateDidFee
	}
	return nil
}

func (m *QuerySSIFeeResponse) GetCreateSchemaFee() *types.Coin {
	if m != nil {
		return m.CreateSchemaFee
	}
	return nil
}

func (m *QuerySSIFeeResponse) GetRegisterCredentialStatusFee() *types.Coin {
	if m != nil {
		return m.RegisterCredentialStatusFee
	}
	return nil
}

func init() {
	proto.RegisterType((*QuerySSIFeeRequest)(nil), "hypersignprotocol.hidnode.identityfee.QuerySSIFeeRequest")
	proto.RegisterType((*QuerySSIFeeResponse)(nil), "hypersignprotocol.hidnode.identityfee.QuerySSIFeeResponse")
}

func init() { proto.RegisterFile("identityfee/v1/query.proto", fileDescriptor_657f65a9c7940d56) }

var fileDescriptor_657f65a9c7940d56 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0x3f, 0x6f, 0xd4, 0x30,
	0x18, 0x06, 0xf0, 0x73, 0x4b, 0x19, 0x5c, 0xc4, 0x9f, 0xd0, 0x01, 0x0e, 0x64, 0xa1, 0x93, 0x10,
	0x30, 0xd4, 0x56, 0xcb, 0x44, 0x17, 0x24, 0x0a, 0x87, 0x18, 0x69, 0x16, 0xc4, 0x40, 0xe4, 0xd8,
	0x6f, 0x13, 0x4b, 0x77, 0x7e, 0xd3, 0xd8, 0xa9, 0xc8, 0xca, 0xc2, 0x8a, 0xc4, 0x97, 0xe0, 0x0b,
	0x30, 0xb3, 0x32, 0x56, 0x62, 0x61, 0x44, 0x39, 0x3e, 0x08, 0x8a, 0x93, 0x96, 0x20, 0x84, 0x82,
	0xba, 0x39, 0x4e, 0x9e, 0xdf, 0x1b, 0xeb, 0x31, 0x9d, 0x1a, 0x0d, 0xd6, 0x1b, 0x5f, 0x1f, 0x02,
	0x88, 0xe3, 0x1d, 0x71, 0x54, 0x41, 0x59, 0xf3, 0xa2, 0x44, 0x8f, 0xd1, 0xdd, 0xbc, 0x2e, 0xa0,
	0x74, 0x26, 0xb3, 0xe1, 0x59, 0xe1, 0x82, 0xe7, 0x46, 0x5b, 0xd4, 0xc0, 0x07, 0xa9, 0xe9, 0xed,
	0x0c, 0x31, 0x5b, 0x80, 0x90, 0x85, 0x11, 0xd2, 0x5a, 0xf4, 0xd2, 0x1b, 0xb4, 0xae, 0x43, 0xa6,
	0x4c, 0xa1, 0x5b, 0xa2, 0x13, 0xa9, 0x74, 0xed, 0x80, 0x14, 0xbc, 0xdc, 0x11, 0x0a, 0x8d, 0xed,
	0xdf, 0x6f, 0x65, 0x98, 0x61, 0x58, 0x8a, 0x76, 0xd5, 0xed, 0xce, 0xb6, 0x68, 0xf4, 0xb2, 0xfd,
	0x93, 0x38, 0x7e, 0x31, 0x07, 0x38, 0x80, 0xa3, 0x0a, 0x9c, 0x9f, 0xbd, 0x5f, 0xa7, 0xd7, 0xff,
	0xd8, 0x76, 0x05, 0x5a, 0x07, 0xd1, 0x63, 0x7a, 0x59, 0x95, 0x20, 0x3d, 0x24, 0xda, 0xe8, 0xe4,
	0x10, 0xe0, 0x06, 0xb9, 0x43, 0xee, 0x6f, 0xee, 0xde, 0xe4, 0xdd, 0x70, 0xde, 0x0e, 0xe7, 0xfd,
	0x70, 0xbe, 0x8f, 0xc6, 0x1e, 0x5c, 0xea, 0x02, 0x4f, 0x8d, 0x9e, 0x43, 0x00, 0xaa, 0x42, 0x0f,
	0x81, 0xb5, 0x51, 0xa0, 0x0b, 0xf4, 0xc0, 0x73, 0x1a, 0x69, 0x90, 0xca, 0x9b, 0xe3, 0x21, 0xb2,
	0x3e, 0x86, 0x5c, 0xfd, 0x1d, 0xea, 0xa1, 0x67, 0xf4, 0x5a, 0x7f, 0x14, 0xa7, 0x72, 0x58, 0xca,
	0xe0, 0x5c, 0x18, 0x73, 0xae, 0x74, 0x99, 0x38, 0x44, 0x5a, 0xe6, 0x0d, 0x65, 0x25, 0x64, 0xc6,
	0x79, 0x28, 0x13, 0x55, 0x42, 0x68, 0x4b, 0x2e, 0x12, 0xe7, 0xa5, 0xaf, 0x5c, 0x30, 0x37, 0xc6,
	0xcc, 0x5b, 0xa7, 0xc0, 0xfe, 0x59, 0x3e, 0x0e, 0xf1, 0x39, 0xc0, 0xee, 0x17, 0x42, 0x37, 0x42,
	0x13, 0xd1, 0x67, 0x42, 0x37, 0x07, 0x9d, 0x44, 0x8f, 0xf8, 0x7f, 0xdd, 0x1a, 0xfe, 0x77, 0xbd,
	0xd3, 0xbd, 0xf3, 0x44, 0xbb, 0x2b, 0x30, 0x13, 0xef, 0xbe, 0xfd, 0xfc, 0xb8, 0xf6, 0x20, 0xba,
	0x27, 0xce, 0x8c, 0xed, 0x53, 0x44, 0xf4, 0x88, 0x18, 0x20, 0x4f, 0x5e, 0x7d, 0x6a, 0x18, 0xf9,
	0xda, 0x30, 0x72, 0xd2, 0x30, 0xf2, 0xa3, 0x61, 0xe4, 0xc3, 0x8a, 0x4d, 0x4e, 0x56, 0x6c, 0xf2,
	0x7d, 0xc5, 0x26, 0xaf, 0xf7, 0x32, 0xe3, 0xf3, 0x2a, 0xe5, 0x0a, 0x97, 0xff, 0x00, 0xb7, 0x83,
	0xf8, 0x76, 0x68, 0x0a, 0x5f, 0x17, 0xe0, 0xd2, 0x8b, 0xe1, 0xb3, 0x87, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xfc, 0xb7, 0xf5, 0x5c, 0x5b, 0x03, 0x00, 0x00,
}

func (this *QuerySSIFeeRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QuerySSIFeeRequest)
	if !ok {
		that2, ok := that.(QuerySSIFeeRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *QuerySSIFeeResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QuerySSIFeeResponse)
	if !ok {
		that2, ok := that.(QuerySSIFeeResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CreateDidFee.Equal(that1.CreateDidFee) {
		return false
	}
	if !this.UpdateDidFee.Equal(that1.UpdateDidFee) {
		return false
	}
	if !this.DeactivateDidFee.Equal(that1.DeactivateDidFee) {
		return false
	}
	if !this.CreateSchemaFee.Equal(that1.CreateSchemaFee) {
		return false
	}
	if !this.RegisterCredentialStatusFee.Equal(that1.RegisterCredentialStatusFee) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Get the list of fixed fees for every x/ssi module transactions
	QuerySSIFee(ctx context.Context, in *QuerySSIFeeRequest, opts ...grpc.CallOption) (*QuerySSIFeeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QuerySSIFee(ctx context.Context, in *QuerySSIFeeRequest, opts ...grpc.CallOption) (*QuerySSIFeeResponse, error) {
	out := new(QuerySSIFeeResponse)
	err := c.cc.Invoke(ctx, "/hypersignprotocol.hidnode.identityfee.Query/QuerySSIFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Get the list of fixed fees for every x/ssi module transactions
	QuerySSIFee(context.Context, *QuerySSIFeeRequest) (*QuerySSIFeeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QuerySSIFee(ctx context.Context, req *QuerySSIFeeRequest) (*QuerySSIFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySSIFee not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QuerySSIFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySSIFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QuerySSIFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hypersignprotocol.hidnode.identityfee.Query/QuerySSIFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QuerySSIFee(ctx, req.(*QuerySSIFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hypersignprotocol.hidnode.identityfee.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuerySSIFee",
			Handler:    _Query_QuerySSIFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identityfee/v1/query.proto",
}

func (m *QuerySSIFeeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySSIFeeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySSIFeeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySSIFeeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySSIFeeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySSIFeeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegisterCredentialStatusFee != nil {
		{
			size, err := m.RegisterCredentialStatusFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.CreateSchemaFee != nil {
		{
			size, err := m.CreateSchemaFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.DeactivateDidFee != nil {
		{
			size, err := m.DeactivateDidFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.UpdateDidFee != nil {
		{
			size, err := m.UpdateDidFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.CreateDidFee != nil {
		{
			size, err := m.CreateDidFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QuerySSIFeeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySSIFeeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreateDidFee != nil {
		l = m.CreateDidFee.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.UpdateDidFee != nil {
		l = m.UpdateDidFee.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.DeactivateDidFee != nil {
		l = m.DeactivateDidFee.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CreateSchemaFee != nil {
		l = m.CreateSchemaFee.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.RegisterCredentialStatusFee != nil {
		l = m.RegisterCredentialStatusFee.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QuerySSIFeeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySSIFeeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySSIFeeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySSIFeeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySSIFeeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySSIFeeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateDidFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreateDidFee == nil {
				m.CreateDidFee = &types.Coin{}
			}
			if err := m.CreateDidFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateDidFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateDidFee == nil {
				m.UpdateDidFee = &types.Coin{}
			}
			if err := m.UpdateDidFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeactivateDidFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeactivateDidFee == nil {
				m.DeactivateDidFee = &types.Coin{}
			}
			if err := m.DeactivateDidFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateSchemaFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreateSchemaFee == nil {
				m.CreateSchemaFee = &types.Coin{}
			}
			if err := m.CreateSchemaFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterCredentialStatusFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterCredentialStatusFee == nil {
				m.RegisterCredentialStatusFee = &types.Coin{}
			}
			if err := m.RegisterCredentialStatusFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
